spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

#    url: jdbc:mysql://192.168.0.40:3306/jpashop
#    url: jdbc:mysql://localhost:3306/jpashop
#    username: root
#    password: apmsetup
#    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mariadb://localhost:3307/jpashop
#    username: root
#    password: apmsetup
#    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace